# Generated by Django 2.2.5 on 2020-11-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_price',
            field=models.PositiveIntegerField(default=10000, verbose_name='小計'),
            preserve_default=False,
        ),
    ]
