# Generated by Django 2.2.5 on 2020-11-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sale_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
